(define-native load-lib!)

(define-native create)
(define-native get-text-size)
(define-native load!)
(define-native load-font)
(define-native load-sprite-map)

(define-native palette/cc)
(define-native palette/riko4)
(define-native palette/redirection)

(define-native surf/clear!)
(define-native surf/copy)
(define-native surf/draw-arc!)
(define-native surf/draw-ellipse!)
(define-native surf/draw-line!)
(define-native surf/draw-pixel!)
(define-native surf/draw-rect!)
(define-native surf/draw-string!)
(define-native surf/draw-surface!)
(define-native surf/draw-surface-rotated!)
(define-native surf/draw-surfaces-interlaced!)
(define-native surf/draw-surface-small!)
(define-native surf/draw-text!)
(define-native surf/draw-triangle!)
(define-native surf/fill-arc!)
(define-native surf/fill-ellipse!)
(define-native surf/fill-rect!)
(define-native surf/fill-triangle!)
(define-native surf/flip!)
(define-native surf/map!)
(define-native surf/output!)
(define-native surf/pop!)
(define-native surf/push!)
(define-native surf/save!)
(define-native surf/shift!)
(define-native surf/to-palette!)
(define-native surf/to-rgb!)

(define-native smap/pos)
(define-native smap/sprite)
